### ISSUE TITLE
Running the dataset for training and eval

### ISSUE THREAD

**Issue by DickHanselRyan** [DanielShalam/BPA#9]
Hi, I am trying to understand your code and running it. I would like to ask, for the training section, if I want to change to CIFAR, do I need to download the dataset again? I already prepare the CIFAR_FS split file as mentioned on datasets readme.md file. But when I tried to run the CIFAR training, it shows error that there's no file/directory.

**Comment by DanielShalam** [comment]
Thanks for your interest !
After downloading the dataset, you need to define the dataset dir in the --data_path argument. 
For example, running - 
python train.py --data_path "./your_cifar_path/CIFAR_FS/" 
with the proper location should initialized the training on CIFAR dataset.

Let me know if you have any more questions.

**Comment by DickHanselRyan** [comment]
Hi, thank you for your fast reply. The CIFAR dataset is working for training now. I would like to ask another question, in the dataset folder, you have a CUB.py file, is it for evaluating the model trained on CIFAR and MiniImageNet or also for training?

**Comment by DickHanselRyan** [comment]
Hi @DanielShalam, I would like to ask, I cannot access or open the checkpoints folder created after running the train.py. I am running it on a server and not my local PC. Or it actually cannot be opened??

**Comment by DanielShalam** [comment]
Hi !
Regarding your first question, 
The CUB.py file is there since we have results on the CUB dataset (seed the results table in the readme file),
but it is also possible to evaluate models trained on other datasets on it.

Regarding your second question,
If you dont see the checkpoint folder in the server you working on the problem might be with the relative path.
Try tweaking the "get_output_dir" function in the utils.py file (specifically line 153) to the absolute path in your server, rather then the relative path provided (the './' prefix define the relative path).
For example, if the absolute path to the root directory is '/root/example/SOT/ ' replace the './' with it.

Hope it helps ! Let me know if you have any more questions.

**Comment by DickHanselRyan** [comment]
Hi @DanielShalam, I'm currently running SOT on my lab's DGX Server. It shows the checkpoint folder. But every time I am trying to open the folder, I cannot access the folder. When I tried to delete the folder, an error popped up as shown in the picture. I've tried to open the folder through my terminal and it works, so I am not sure what is happening. I already disabled the Wandb and don't use it. Or should I use the Wandb?

![method not allowed](https://github.com/DanielShalam/SOT/assets/83385410/cae567c1-220d-41c1-a0e3-881d1ffd35ea)
